name: Backend Pipeline
on:
  push:
    paths:
      - "backend/**"
  pull_request:
    branches:
      - "MS*"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: menuproject
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./backend/menuproject
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: "3.8.4"
      - name: Wait for PostgreSQL
        run: sleep 10
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Compile with Maven
        run: ./mvnw clean compile
      - name: view the compiled files
        run: find target/classes -type f
      - name: Run SonarQube Analysis with Maven
        run: mvn verify sonar:sonar -Dsonar.projectKey=fitito1234_menuproject -Dsonar.organization=fitito1234 -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Scan
        run: mvn verify sonar:sonar
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/menuproject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
